<a href="https://colab.research.google.com/github/kimyt1976/AI-Programming/blob/main/14%EC%A3%BC%EC%B0%A8_FrozenLake_%EB%AC%B8%EC%A0%9C%EC%97%90%EC%84%9C_%EA%B0%80%EC%B9%98%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import gym
import numpy as np

env = gym.make('FrozenLake-v1', is_slippery=False)
Q=np.zeros([env.observation_space.n,env.action_space.n])     #Q배열 초기화

rho=0.90              #학습율
lamda=0.99            #할인율
eps=1.0               #앱실론
eps_decay=0.999       #삭감비율

n_episode=3000
length_episode=100

#최적 행동 가치함수 찾기(탐사와 탐험의 균형 추구)
for i in range(n_episode):
  s=env.reset()          #새로운 에피소드 시작
  for j in range(length_episode):
    r=np.random.random()
    eps=max(0.01,eps*eps_decay)        #앱실론 조금씩 줄여나감
    if(r<eps):                         #erp 비율만큼 임의 선택
      a=np.random.randint(0,env.action_space.n)
    else:
      argmaxs=np.argwhere(Q[s,:]==np.amax(Q[s,:])).flatten().tolist()
      a=np.random.choice(argmaxs)
    s1,r,done,_=env.step(a)
    Q[s,a]=Q[s,a]+rho*(r+lamda*np.max(Q[s1,:])-Q[s,a])
    s=s1
    if done:
      break

np.set_printoptions(precision=2)
print(Q)

[[0.94 0.93 0.95 0.94]
 [0.94 0.   0.96 0.95]
 [0.95 0.97 0.95 0.96]
 [0.96 0.   0.   0.86]
 [0.   0.   0.   0.94]
 [0.   0.   0.   0.  ]
 [0.   0.98 0.   0.96]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.93]
 [0.92 0.   0.   0.  ]
 [0.91 0.99 0.   0.97]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.99 0.  ]
 [0.98 0.99 1.   0.98]
 [0.   0.   0.   0.  ]]
