<a href="https://colab.research.google.com/github/kimyt1976/AI-Programming/blob/main/%ED%95%B4%EC%96%91%EB%8C%80%EA%B3%BC%EC%A0%9C3%EC%A3%BC%EC%B0%A82%EB%B2%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
print("샘플")
import numpy as np
#3 차원 배열의 크기를 지정합니다
shape = (3, 4, 5)
# 3차원 배열을 생성합니다
arr = np.random.randint(0, 10, shape)
# 3차원 배열을 출력합니다
print(arr)

# 1.shape 가 (3, 3, 6) 이고 , 배열 원소가 0~20 사이의 정수 값을 갖도록 임의의 3 차원 배열을 만드세요
print("1번문제")
import numpy as np
#3 차원 배열의 크기를 지정합니다
shape = (3, 3, 6)
# 3차원 배열을 생성합니다
arr = np.random.randint(0, 20, shape)
# 3차원 배열을 출력합니다
print(arr)

# 2.shape 가 (5, 6) 이고 , 배열 원소가 0~100 사이의 정수 값을 갖도록 임의의 2 차원 배열을만드세요
print("2번문제")
import numpy as np
#3 차원 배열의 크기를 지정합니다
shape = (5, 6)
# 3차원 배열을 생성합니다
arr = np.random.randint(0, 100, shape)
# 3차원 배열을 출력합니다
print(arr)

샘플
[[[9 3 5 0 9]
  [4 4 7 6 1]
  [3 8 0 4 8]
  [9 8 1 2 7]]

 [[3 8 1 6 7]
  [7 3 0 9 7]
  [0 4 3 0 5]
  [7 4 8 9 5]]

 [[7 7 4 8 4]
  [4 6 1 3 5]
  [1 7 3 0 3]
  [8 5 8 8 0]]]
1번문제
[[[ 1 19  0 19 15 16]
  [14 10  1 14 12  0]
  [ 3  0  4  7 12  4]]

 [[14 15  3 17 13 17]
  [10 15 16  3 10  5]
  [ 0  6 19  4 15 16]]

 [[14  8  4  8  0  1]
  [ 2 15 16 12  5  6]
  [ 9 14  9  7 11  6]]]
2번문제
[[68 36 13 62 53 44]
 [ 2  2 91 50 35 76]
 [47  0 31 52  9 74]
 [35 29 31  6 16 28]
 [37 71 72 95 91  8]]
