<a href="https://colab.research.google.com/github/kimyt1976/AI-Programming/blob/main/%ED%95%B4%EC%96%91%EB%8C%80%EA%B3%BC%EC%A0%9C3%EC%A3%BC%EC%B0%A8_1%EB%B2%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np

np.random.seed(85)
a = np.arange (1,46)

lista=[]
num = 1

while num < 4:
  np.random.shuffle(a)
  lotto = a[:6]
  print('lotto = ', lotto)
  lista.extend(lotto)
  num = num + 1
myarray = np.array(lista)
myarray2 = b.reshape(3,6)
print (myarray2)


lotto =  [22  9 15 44 39 37]
lotto =  [ 2 12 10 20 17 19]
lotto =  [37 10 16 31 35 15]
[[22  9 15 44 39 37]
 [ 2 12 10 20 17 19]
 [37 10 16 31 35 15]]
